
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 10 10:53:20 CET 2026
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sat Jan 10 10:53:20 CET 2026
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\203\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\003\004\000\002\003\003\000\002\004\006" +
    "\000\002\005\006\000\002\006\006\000\002\007\015\000" +
    "\002\103\003\000\002\103\002\000\002\104\003\000\002" +
    "\104\002\000\002\105\003\000\002\105\002\000\002\106" +
    "\003\000\002\106\002\000\002\107\003\000\002\107\002" +
    "\000\002\110\003\000\002\110\002\000\002\111\003\000" +
    "\002\111\002\000\002\112\003\000\002\112\002\000\002" +
    "\113\003\000\002\113\002\000\002\114\003\000\002\114" +
    "\002\000\002\115\003\000\002\115\002\000\002\116\003" +
    "\000\002\116\002\000\002\117\003\000\002\117\002\000" +
    "\002\120\003\000\002\120\002\000\002\121\003\000\002" +
    "\121\002\000\002\010\012\000\002\011\006\000\002\011" +
    "\006\000\002\012\006\000\002\013\010\000\002\014\006" +
    "\000\002\014\006\000\002\015\010\000\002\016\006\000" +
    "\002\017\006\000\002\020\006\000\002\020\005\000\002" +
    "\020\004\000\002\021\006\000\002\022\006\000\002\023" +
    "\006\000\002\024\007\000\002\024\006\000\002\054\004" +
    "\000\002\054\003\000\002\055\004\000\002\055\003\000" +
    "\002\056\003\000\002\056\002\000\002\025\007\000\002" +
    "\057\004\000\002\057\003\000\002\061\003\000\002\061" +
    "\002\000\002\060\004\000\002\060\003\000\002\026\012" +
    "\000\002\027\006\000\002\027\006\000\002\030\006\000" +
    "\002\030\006\000\002\031\006\000\002\031\006\000\002" +
    "\032\006\000\002\032\006\000\002\033\006\000\002\062" +
    "\004\000\002\062\003\000\002\034\010\000\002\035\006" +
    "\000\002\036\012\000\002\037\006\000\002\041\011\000" +
    "\002\042\006\000\002\042\006\000\002\043\006\000\002" +
    "\043\006\000\002\044\011\000\002\045\006\000\002\045" +
    "\006\000\002\046\007\000\002\046\006\000\002\063\004" +
    "\000\002\063\003\000\002\064\003\000\002\064\002\000" +
    "\002\047\007\000\002\067\005\000\002\067\002\000\002" +
    "\050\006\000\002\065\004\000\002\065\003\000\002\051" +
    "\006\000\002\052\006\000\002\052\006\000\002\053\011" +
    "\000\002\066\005\000\002\066\006\000\002\074\007\000" +
    "\002\074\006\000\002\070\004\000\002\070\003\000\002" +
    "\071\004\000\002\071\003\000\002\072\003\000\002\072" +
    "\002\000\002\075\013\000\002\076\006\000\002\076\006" +
    "\000\002\077\006\000\002\073\004\000\002\073\003\000" +
    "\002\100\007\000\002\101\006\000\002\101\006\000\002" +
    "\102\007\000\002\040\006" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\u0143\000\006\004\005\005\007\001\002\000\006\002" +
    "\ufffd\004\005\001\002\000\004\101\023\001\002\000\004" +
    "\002\uffff\001\002\000\004\063\014\001\002\000\004\002" +
    "\013\001\002\000\004\004\005\001\002\000\004\002\000" +
    "\001\002\000\004\002\001\001\002\000\004\101\016\001" +
    "\002\000\004\064\022\001\002\000\004\067\017\001\002" +
    "\000\004\105\020\001\002\000\004\070\021\001\002\000" +
    "\004\064\ufffa\001\002\000\004\004\ufffc\001\002\000\004" +
    "\063\024\001\002\000\004\006\025\001\002\000\004\063" +
    "\u0142\001\002\000\004\007\027\001\002\000\004\063\u0116" +
    "\001\002\000\004\023\031\001\002\000\004\063\343\001" +
    "\002\000\014\034\033\037\ufff7\045\ufff7\053\ufff7\064\ufff7" +
    "\001\002\000\004\063\315\001\002\000\012\037\ufff8\045" +
    "\ufff8\053\ufff8\064\ufff8\001\002\000\012\037\037\045\ufff5" +
    "\053\ufff5\064\ufff5\001\002\000\010\045\ufff6\053\ufff6\064" +
    "\ufff6\001\002\000\004\063\235\001\002\000\010\045\041" +
    "\053\ufff3\064\ufff3\001\002\000\004\063\206\001\002\000" +
    "\006\053\ufff4\064\ufff4\001\002\000\006\053\044\064\ufff1" +
    "\001\002\000\004\063\050\001\002\000\004\064\047\001" +
    "\002\000\004\064\ufff2\001\002\000\006\002\ufff9\004\ufff9" +
    "\001\002\000\006\054\054\061\055\001\002\000\006\061" +
    "\uff8c\064\uff8c\001\002\000\006\061\055\064\205\001\002" +
    "\000\010\054\054\061\055\064\uff8a\001\002\000\004\063" +
    "\077\001\002\000\004\063\057\001\002\000\010\054\uff8e" +
    "\061\uff8e\064\uff8e\001\002\000\004\055\060\001\002\000" +
    "\004\065\072\001\002\000\004\027\063\001\002\000\004" +
    "\064\071\001\002\000\004\065\064\001\002\000\006\101" +
    "\065\105\066\001\002\000\004\066\070\001\002\000\004" +
    "\066\067\001\002\000\014\012\uffb6\030\uffb6\033\uffb6\052" +
    "\uffb6\064\uffb6\001\002\000\014\012\uffb5\030\uffb5\033\uffb5" +
    "\052\uffb5\064\uffb5\001\002\000\006\061\uff80\064\uff80\001" +
    "\002\000\006\101\073\105\074\001\002\000\004\066\076" +
    "\001\002\000\004\066\075\001\002\000\012\027\uff88\036" +
    "\uff88\050\uff88\056\uff88\001\002\000\012\027\uff87\036\uff87" +
    "\050\uff87\056\uff87\001\002\000\004\055\060\001\002\000" +
    "\006\027\uffdb\056\102\001\002\000\004\027\uffdc\001\002" +
    "\000\004\063\153\001\002\000\004\027\063\001\002\000" +
    "\004\052\105\001\002\000\004\063\125\001\002\000\004" +
    "\060\110\001\002\000\006\022\120\064\uffe9\001\002\000" +
    "\004\065\111\001\002\000\006\101\112\105\113\001\002" +
    "\000\004\066\115\001\002\000\004\066\114\001\002\000" +
    "\006\022\uff82\064\uff82\001\002\000\006\022\uff81\064\uff81" +
    "\001\002\000\004\064\uffea\001\002\000\004\064\124\001" +
    "\002\000\004\065\121\001\002\000\004\075\122\001\002" +
    "\000\004\066\123\001\002\000\004\064\uffcb\001\002\000" +
    "\010\054\uff89\061\uff89\064\uff89\001\002\000\004\055\060" +
    "\001\002\000\004\050\127\001\002\000\004\065\146\001" +
    "\002\000\004\051\131\001\002\000\004\065\143\001\002" +
    "\000\004\071\134\001\002\000\006\064\137\071\140\001" +
    "\002\000\004\050\127\001\002\000\004\051\131\001\002" +
    "\000\006\064\uff93\071\uff93\001\002\000\010\052\uff94\060" +
    "\uff94\064\uff94\001\002\000\004\050\127\001\002\000\004" +
    "\051\131\001\002\000\006\064\uff92\071\uff92\001\002\000" +
    "\004\072\144\001\002\000\004\066\145\001\002\000\006" +
    "\064\uff97\071\uff97\001\002\000\006\101\147\105\150\001" +
    "\002\000\004\066\152\001\002\000\004\066\151\001\002" +
    "\000\010\051\uff96\064\uff96\071\uff96\001\002\000\010\051" +
    "\uff95\064\uff95\071\uff95\001\002\000\004\057\155\001\002" +
    "\000\006\057\155\064\176\001\002\000\004\063\157\001" +
    "\002\000\006\057\uff84\064\uff84\001\002\000\004\010\160" +
    "\001\002\000\004\065\171\001\002\000\006\021\163\064" +
    "\uffeb\001\002\000\004\064\170\001\002\000\004\065\165" +
    "\001\002\000\006\022\uffec\064\uffec\001\002\000\004\075" +
    "\166\001\002\000\004\066\167\001\002\000\006\022\uffcc" +
    "\064\uffcc\001\002\000\006\057\uff83\064\uff83\001\002\000" +
    "\006\101\173\104\172\001\002\000\004\066\175\001\002" +
    "\000\004\066\174\001\002\000\012\011\uffd8\012\uffd8\021" +
    "\uffd8\064\uffd8\001\002\000\012\011\uffd9\012\uffd9\021\uffd9" +
    "\064\uffd9\001\002\000\004\027\uff86\001\002\000\006\057" +
    "\uff85\064\uff85\001\002\000\006\061\055\064\uff8b\001\002" +
    "\000\004\064\203\001\002\000\010\054\uff8f\061\uff8f\064" +
    "\uff8f\001\002\000\004\064\uff91\001\002\000\006\061\uff8d" +
    "\064\uff8d\001\002\000\004\064\uff90\001\002\000\006\046" +
    "\212\047\211\001\002\000\006\047\211\064\234\001\002" +
    "\000\006\047\211\064\uff9e\001\002\000\004\063\223\001" +
    "\002\000\004\063\214\001\002\000\006\047\uffa0\064\uffa0" +
    "\001\002\000\004\050\127\001\002\000\006\064\uff9b\071" +
    "\217\001\002\000\004\064\222\001\002\000\004\050\127" +
    "\001\002\000\006\064\uff9b\071\217\001\002\000\004\064" +
    "\uff9c\001\002\000\006\047\uff9d\064\uff9d\001\002\000\004" +
    "\052\105\001\002\000\006\052\105\064\226\001\002\000" +
    "\006\052\uff98\064\uff98\001\002\000\006\047\uff9a\064\uff9a" +
    "\001\002\000\006\052\uff99\064\uff99\001\002\000\006\047" +
    "\211\064\uff9f\001\002\000\004\064\232\001\002\000\006" +
    "\053\uffa3\064\uffa3\001\002\000\006\047\uffa1\064\uffa1\001" +
    "\002\000\006\053\uffa2\064\uffa2\001\002\000\006\040\240" +
    "\043\243\001\002\000\006\043\243\064\314\001\002\000" +
    "\010\040\240\043\243\064\uffc3\001\002\000\004\063\272" +
    "\001\002\000\006\043\uffc5\064\uffc5\001\002\000\010\040" +
    "\uffc7\043\uffc7\064\uffc7\001\002\000\004\063\244\001\002" +
    "\000\004\041\245\001\002\000\004\065\265\001\002\000" +
    "\004\027\063\001\002\000\004\033\250\001\002\000\004" +
    "\065\262\001\002\000\004\044\252\001\002\000\004\065" +
    "\255\001\002\000\004\064\254\001\002\000\006\043\uffa6" +
    "\064\uffa6\001\002\000\006\101\256\105\257\001\002\000" +
    "\004\066\261\001\002\000\004\066\260\001\002\000\006" +
    "\042\uffa5\064\uffa5\001\002\000\006\042\uffa4\064\uffa4\001" +
    "\002\000\004\062\263\001\002\000\004\066\264\001\002" +
    "\000\006\012\uff7f\044\uff7f\001\002\000\006\101\266\105" +
    "\267\001\002\000\004\066\271\001\002\000\004\066\270" +
    "\001\002\000\006\027\uffaa\033\uffaa\001\002\000\006\027" +
    "\uffa9\033\uffa9\001\002\000\004\041\245\001\002\000\004" +
    "\033\250\001\002\000\004\044\252\001\002\000\006\042" +
    "\300\064\uffdf\001\002\000\004\064\uffe0\001\002\000\004" +
    "\064\306\001\002\000\004\065\301\001\002\000\006\101" +
    "\302\105\303\001\002\000\004\066\305\001\002\000\004" +
    "\066\304\001\002\000\004\064\uffa8\001\002\000\004\064" +
    "\uffa7\001\002\000\010\040\uffab\043\uffab\064\uffab\001\002" +
    "\000\006\043\243\064\uffc4\001\002\000\004\064\312\001" +
    "\002\000\010\040\uffc8\043\uffc8\064\uffc8\001\002\000\010" +
    "\045\uffca\053\uffca\064\uffca\001\002\000\006\043\uffc6\064" +
    "\uffc6\001\002\000\010\045\uffc9\053\uffc9\064\uffc9\001\002" +
    "\000\004\035\316\001\002\000\004\063\323\001\002\000" +
    "\006\035\uffb0\064\uffb0\001\002\000\006\035\316\064\322" +
    "\001\002\000\006\035\uffb1\064\uffb1\001\002\000\012\037" +
    "\uffb2\045\uffb2\053\uffb2\064\uffb2\001\002\000\004\055\060" +
    "\001\002\000\004\036\326\001\002\000\006\026\332\064" +
    "\uffe7\001\002\000\004\065\327\001\002\000\004\073\330" +
    "\001\002\000\004\066\331\001\002\000\006\026\uffae\064" +
    "\uffae\001\002\000\004\065\336\001\002\000\004\064\uffe8" +
    "\001\002\000\004\064\335\001\002\000\006\035\uffaf\064" +
    "\uffaf\001\002\000\006\101\340\104\337\001\002\000\004" +
    "\066\342\001\002\000\004\066\341\001\002\000\014\012" +
    "\uffb7\027\uffb7\030\uffb7\033\uffb7\064\uffb7\001\002\000\014" +
    "\012\uffb8\027\uffb8\030\uffb8\033\uffb8\064\uffb8\001\002\000" +
    "\004\024\346\001\002\000\010\024\346\031\u0105\064\uffbe" +
    "\001\002\000\010\024\uffc0\031\uffc0\064\uffc0\001\002\000" +
    "\004\063\347\001\002\000\004\025\350\001\002\000\004" +
    "\065\375\001\002\000\004\026\332\001\002\000\010\012" +
    "\uffe5\027\063\030\uffe5\001\002\000\006\012\uffe6\030\uffe6" +
    "\001\002\000\006\012\uffe3\030\357\001\002\000\004\012" +
    "\uffe4\001\002\000\004\012\366\001\002\000\004\065\360" +
    "\001\002\000\006\101\361\105\362\001\002\000\004\066" +
    "\364\001\002\000\004\066\363\001\002\000\004\012\uffb4" +
    "\001\002\000\004\012\uffb3\001\002\000\004\064\374\001" +
    "\002\000\004\065\367\001\002\000\004\076\370\001\002" +
    "\000\004\077\371\001\002\000\004\100\372\001\002\000" +
    "\004\066\373\001\002\000\010\013\uffd6\014\uffd6\064\uffd6" +
    "\001\002\000\010\024\uffbb\031\uffbb\064\uffbb\001\002\000" +
    "\006\101\377\104\376\001\002\000\004\066\u0101\001\002" +
    "\000\004\066\u0100\001\002\000\006\026\uffb9\032\uffb9\001" +
    "\002\000\006\026\uffba\032\uffba\001\002\000\006\031\u0105" +
    "\064\uffbf\001\002\000\006\031\uffbc\064\uffbc\001\002\000" +
    "\010\024\uffc1\031\uffc1\064\uffc1\001\002\000\004\063\u0108" +
    "\001\002\000\004\064\u0107\001\002\000\014\034\uffc2\037" +
    "\uffc2\045\uffc2\053\uffc2\064\uffc2\001\002\000\004\025\350" +
    "\001\002\000\006\026\uffdd\032\u010b\001\002\000\004\026" +
    "\uffde\001\002\000\004\065\u0112\001\002\000\004\026\332" +
    "\001\002\000\006\012\uffe1\033\250\001\002\000\004\012" +
    "\uffe2\001\002\000\004\012\366\001\002\000\004\064\u0111" +
    "\001\002\000\006\031\uffad\064\uffad\001\002\000\004\102" +
    "\u0113\001\002\000\004\066\u0114\001\002\000\004\026\uffac" +
    "\001\002\000\006\031\uffbd\064\uffbd\001\002\000\004\010" +
    "\160\001\002\000\006\011\u0118\012\uffef\001\002\000\004" +
    "\065\u013f\001\002\000\004\012\ufff0\001\002\000\004\012" +
    "\366\001\002\000\006\013\u011c\014\uffed\001\002\000\004" +
    "\065\u013a\001\002\000\004\014\uffee\001\002\000\004\014" +
    "\u0120\001\002\000\004\064\u0139\001\002\000\004\063\u0121" +
    "\001\002\000\004\015\u0122\001\002\000\004\065\u0136\001" +
    "\002\000\004\016\u0125\001\002\000\004\017\u012a\001\002" +
    "\000\004\065\u0126\001\002\000\004\103\u0127\001\002\000" +
    "\004\066\u0128\001\002\000\004\017\uffd1\001\002\000\004" +
    "\064\u0135\001\002\000\010\020\u012c\021\163\022\120\001" +
    "\002\000\004\064\uffce\001\002\000\004\065\u0132\001\002" +
    "\000\006\022\120\064\uffe9\001\002\000\010\021\163\022" +
    "\uffeb\064\uffeb\001\002\000\006\022\120\064\uffe9\001\002" +
    "\000\004\064\uffd0\001\002\000\004\064\uffcf\001\002\000" +
    "\004\075\u0133\001\002\000\004\066\u0134\001\002\000\010" +
    "\021\uffcd\022\uffcd\064\uffcd\001\002\000\004\064\uffd3\001" +
    "\002\000\004\074\u0137\001\002\000\004\066\u0138\001\002" +
    "\000\004\016\uffd2\001\002\000\004\023\uffda\001\002\000" +
    "\006\101\u013b\105\u013c\001\002\000\004\066\u013e\001\002" +
    "\000\004\066\u013d\001\002\000\004\014\uffd5\001\002\000" +
    "\004\014\uffd4\001\002\000\004\075\u0140\001\002\000\004" +
    "\066\u0141\001\002\000\004\012\uffd7\001\002\000\004\101" +
    "\016\001\002\000\004\064\u0144\001\002\000\004\007\ufffb" +
    "\001\002\000\004\002\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\u0143\000\012\002\007\003\005\004\010\007\003\001" +
    "\001\000\006\003\u0144\007\003\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\003\011\007\003\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\006\014\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\005" +
    "\025\001\001\000\002\001\001\000\004\010\027\001\001" +
    "\000\002\001\001\000\004\025\031\001\001\000\002\001" +
    "\001\000\006\033\033\103\034\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\024\035\104\037\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\046\041\105\042" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\074" +
    "\045\106\044\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\070\052\071" +
    "\051\075\055\102\050\001\001\000\002\001\001\000\004" +
    "\102\203\001\001\000\012\071\177\072\200\075\201\102" +
    "\050\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\076\060\001\001\000\002\001\001\000" +
    "\004\031\061\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\076\077\001\001\000\006" +
    "\077\100\121\102\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\031\103\001\001\000\004\053\105\001\001" +
    "\000\002\001\001\000\004\101\106\001\001\000\006\023" +
    "\115\112\116\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\076\125\001\001\000\004" +
    "\052\127\001\001\000\002\001\001\000\004\051\131\001" +
    "\001\000\002\001\001\000\004\066\132\001\001\000\002" +
    "\001\001\000\004\052\134\001\001\000\004\051\135\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\052\140" +
    "\001\001\000\004\051\141\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\073\153\100\155\001\001" +
    "\000\004\100\176\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\011\160\001\001\000\002\001\001\000\006" +
    "\022\163\111\161\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\102" +
    "\203\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\047" +
    "\207\050\212\063\206\001\001\000\004\050\232\001\001" +
    "\000\010\050\212\063\227\064\230\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\052\214" +
    "\001\001\000\004\067\215\001\001\000\002\001\001\000" +
    "\004\052\217\001\001\000\004\067\220\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\053\224\065\223\001" +
    "\001\000\004\053\226\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\050\232\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\041\241\044\240\054\236\055\235\001" +
    "\001\000\004\044\312\001\001\000\012\041\310\044\240" +
    "\055\306\056\307\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\042\245" +
    "\001\001\000\002\001\001\000\004\031\246\001\001\000" +
    "\004\040\250\001\001\000\002\001\001\000\004\045\252" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\042\272\001\001\000\004\040\273\001\001" +
    "\000\004\045\274\001\001\000\006\043\275\117\276\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\044\312\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\034\316\062\317\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\034\320\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\076\323\001\001\000\004\035\324\001" +
    "\001\000\006\030\332\113\333\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\026\344" +
    "\057\343\001\001\000\012\026\u0103\036\u0102\060\u0101\061" +
    "\u0105\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\027\350\001\001\000\002\001\001\000\004\030\351\001" +
    "\001\000\006\031\352\114\353\001\001\000\002\001\001" +
    "\000\006\032\354\115\355\001\001\000\002\001\001\000" +
    "\004\013\364\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\036\u0114\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\027\u0108\001\001\000\006\037\u0109" +
    "\120\u010b\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\030\u010c\001\001\000\006\040\u010d\116\u010e\001\001" +
    "\000\002\001\001\000\004\013\u010f\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\011\u0116\001" +
    "\001\000\006\012\u0118\107\u0119\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\013\u011a\001\001\000\006\014" +
    "\u011c\110\u011d\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\015\u011e\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\016\u0122\001\001\000\002\001\001\000\004" +
    "\017\u0123\001\001\000\004\020\u0128\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\021\u012d\022\u012c\023\u012a\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\023\115" +
    "\112\u0130\001\001\000\006\022\163\111\u012e\001\001\000" +
    "\006\023\115\112\u012f\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\006\u0142\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public static void main(String args[]) throws Exception {
        FileInputStream stream = new FileInputStream(args[0]);
        Reader reader = new InputStreamReader(stream);

        try {
            new parser(new Yylex(reader)).parse();
        } catch (Exception e) {
            System.out.println("Analisis INCORRECTO !!");
            System.exit(1);
        }
        System.out.println("Analisis Correcto ");
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 130: // horas ::= HORAS PA_A NUM PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("horas",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 129: // merito ::= MERITOS LL_A nombre descripcion LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("merito",64, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 128: // tecnologias ::= TECNOLOGIAS PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tecnologias",63, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 127: // tecnologias ::= TECNOLOGIAS PA_A CONJPALYNUM PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tecnologias",63, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 126: // companero ::= COMPANERO LL_A nomyape github_opt LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("companero",62, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 125: // companero_list ::= companero 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("companero_list",57, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 124: // companero_list ::= companero_list companero 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("companero_list",57, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 123: // grupo ::= GRUPO LL_A companero_list LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("grupo",61, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 122: // nombre ::= NOMBRE PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nombre",60, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 121: // nombre ::= NOMBRE PA_A CONJPALYNUM PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nombre",60, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 120: // proyecto ::= PROYECTO LL_A nombre grupo_opt descripcion categoria tecnologias web_opt LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("proyecto",59, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 119: // merito_opt_list ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("merito_opt_list",56, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 118: // merito_opt_list ::= merito_list 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("merito_opt_list",56, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 117: // merito_list ::= merito 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("merito_list",55, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 116: // merito_list ::= merito_list merito 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("merito_list",55, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 115: // proyecto_list ::= proyecto 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("proyecto_list",54, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 114: // proyecto_list ::= proyecto_list proyecto 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("proyecto_list",54, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 113: // portafolio ::= PORTAFOLIO LL_A merito_list LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("portafolio",58, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 112: // portafolio ::= PORTAFOLIO LL_A proyecto_list merito_opt_list LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("portafolio",58, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 111: // categoria_tail ::= categoria_tail CO habilidad nvh 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("categoria_tail",52, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 110: // categoria_tail ::= CO habilidad nvh 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("categoria_tail",52, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 109: // categoria ::= CATEGORIA LL_A nombre habilidad nvh categoria_tail LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("categoria",41, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 108: // habilidad ::= HABILIDAD PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("habilidad",40, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 107: // habilidad ::= HABILIDAD PA_A CONJPALYNUM PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("habilidad",40, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 106: // nvh ::= NVHAB PA_A NVH PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nvh",39, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 105: // categoria_list ::= categoria 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("categoria_list",51, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 104: // categoria_list ::= categoria_list categoria 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("categoria_list",51, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 103: // hard ::= HARD LL_A categoria_list LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("hard",38, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 102: // soft_hab_tail ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("soft_hab_tail",53, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 101: // soft_hab_tail ::= CO habilidad soft_hab_tail 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("soft_hab_tail",53, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 100: // soft ::= SOFT LL_A habilidad soft_hab_tail LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("soft",37, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 99: // hard_opt_list ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("hard_opt_list",50, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 98: // hard_opt_list ::= hard_list 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("hard_opt_list",50, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 97: // hard_list ::= hard 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("hard_list",49, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 96: // hard_list ::= hard_list hard 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("hard_list",49, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 95: // habilidades ::= HABILIDADES LL_A hard_list LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("habilidades",36, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 94: // habilidades ::= HABILIDADES LL_A soft hard_opt_list LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("habilidades",36, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // organizacion ::= ORGANIZACION PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("organizacion",35, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // organizacion ::= ORGANIZACION PA_A CONJPALYNUM PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("organizacion",35, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // voluntariado ::= VOLUNTARIADO LL_A puesto descripcion horas organizacion LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("voluntariado",34, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // responsabilidades ::= RESPONSABILIDADES PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("responsabilidades",33, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // responsabilidades ::= RESPONSABILIDADES PA_A CONJPALYNUM PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("responsabilidades",33, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // puesto ::= PUESTO PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("puesto",32, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // puesto ::= PUESTO PA_A CONJPALYNUM PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("puesto",32, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // laboral ::= LABORAL LL_A puesto horas organizacion responsabilidades_opt LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("laboral",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // certificado ::= CERTIFICADO PA_A BOOL PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("certificado",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // complementaria ::= COMPLEMENTARIA LL_A titulo certificado_opt expedidor horas_opt fecha LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("complementaria",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // nvi ::= NIVEL PA_A NVI PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nvi",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // idioma ::= IDIOMA LL_A nombre nvi expedidor_opt LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("idioma",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // idioma_list ::= idioma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("idioma_list",48, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // idioma_list ::= idioma_list idioma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("idioma_list",48, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // idiomas ::= IDIOMAS LL_A idioma_list LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("idiomas",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // logros ::= LOGROS PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("logros",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // logros ::= LOGROS PA_A CONJPALYNUM PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("logros",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // descripcion ::= DESCRIPCION PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("descripcion",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // descripcion ::= DESCRIPCION PA_A CONJPALYNUM PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("descripcion",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // expedidor ::= EXPEDIDOR PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expedidor",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // expedidor ::= EXPEDIDOR PA_A CONJPAL PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expedidor",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // titulo ::= TITULO PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("titulo",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // titulo ::= TITULO PA_A CONJPAL PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("titulo",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // oficial ::= OFICIAL LL_A titulo expedidor descripcion_opt logros_opt fecha LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("oficial",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // complementaria_list ::= complementaria 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("complementaria_list",46, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // complementaria_list ::= complementaria_list complementaria 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("complementaria_list",46, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // complementaria_opt_list ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("complementaria_opt_list",47, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // complementaria_opt_list ::= complementaria_list 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("complementaria_opt_list",47, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // oficial_list ::= oficial 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("oficial_list",45, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // oficial_list ::= oficial_list oficial 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("oficial_list",45, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // formacion ::= FORMACION LL_A oficial_list complementaria_opt_list LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("formacion",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // voluntariado_opt_list ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("voluntariado_opt_list",44, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // voluntariado_opt_list ::= voluntariado_list 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("voluntariado_opt_list",44, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // voluntariado_list ::= voluntariado 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("voluntariado_list",43, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // voluntariado_list ::= voluntariado_list voluntariado 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("voluntariado_list",43, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // laboral_list ::= laboral 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("laboral_list",42, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // laboral_list ::= laboral_list laboral 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("laboral_list",42, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // experiencia ::= EXPERIENCIA LL_A voluntariado_list LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("experiencia",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // experiencia ::= EXPERIENCIA LL_A laboral_list voluntariado_opt_list LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("experiencia",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // web ::= WEB PA_A RUTA PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("web",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // github ::= GITHUB PA_A RUTA PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("github",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // linkedin ::= LINKEDIN PA_A RUTA PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("linkedin",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // redes ::= REDES web 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("redes",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // redes ::= REDES github web_opt 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("redes",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // redes ::= REDES linkedin github_opt web_opt 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("redes",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // telefono ::= TELEFONO PA_A TFNO PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("telefono",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // email ::= EMAIL PA_A MAIL PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("email",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // contacto ::= CONTACTO LL_A email telefono redes LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("contacto",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // bio ::= BIO PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bio",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // bio ::= BIO PA_A CONJPALYNUM PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bio",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // fecha ::= FECHA PA_A DIA MES ANIO PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("fecha",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // foto ::= FOTO PA_A RUTA PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("foto",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // nomyape ::= NOMYAPE PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nomyape",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // nomyape ::= NOMYAPE PA_A CONJPAL PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nomyape",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // datospersonales ::= DP LL_A nomyape foto_opt fecha bio_opt contacto LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("datospersonales",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // grupo_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("grupo_opt",79, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // grupo_opt ::= grupo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("grupo_opt",79, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // certificado_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("certificado_opt",78, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // certificado_opt ::= certificado 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("certificado_opt",78, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // responsabilidades_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("responsabilidades_opt",77, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // responsabilidades_opt ::= responsabilidades 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("responsabilidades_opt",77, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // horas_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("horas_opt",76, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // horas_opt ::= horas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("horas_opt",76, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // logros_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("logros_opt",75, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // logros_opt ::= logros 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("logros_opt",75, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // descripcion_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("descripcion_opt",74, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // descripcion_opt ::= descripcion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("descripcion_opt",74, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expedidor_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expedidor_opt",73, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expedidor_opt ::= expedidor 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expedidor_opt",73, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // web_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("web_opt",72, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // web_opt ::= web 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("web_opt",72, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // github_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("github_opt",71, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // github_opt ::= github 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("github_opt",71, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // bio_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bio_opt",70, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // bio_opt ::= bio 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bio_opt",70, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // foto_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("foto_opt",69, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // foto_opt ::= foto 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("foto_opt",69, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // portafolio_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("portafolio_opt",68, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // portafolio_opt ::= portafolio 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("portafolio_opt",68, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // habilidades_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("habilidades_opt",67, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // habilidades_opt ::= habilidades 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("habilidades_opt",67, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // experiencia_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("experiencia_opt",66, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // experiencia_opt ::= experiencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("experiencia_opt",66, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // idiomas_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("idiomas_opt",65, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // idiomas_opt ::= idiomas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("idiomas_opt",65, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // cv ::= CV IDENT LL_A local_var datospersonales formacion idiomas_opt experiencia_opt habilidades_opt portafolio_opt LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cv",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // variable ::= IDENT IG CONJPALYNUM PYC 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("variable",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // local_var ::= LVAR LL_A variable LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("local_var",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // global_var ::= GVAR LL_A variable LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("global_var",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // cv_list ::= cv 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cv_list",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // cv_list ::= cv cv_list 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cv_list",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // cvs ::= cv_list 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cvs",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // cvs ::= global_var cv_list 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cvs",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= cvs EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

