
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\201\000\002\002\004\000\002\004\004\000\002\004" +
    "\003\000\002\005\007\000\002\005\006\000\002\006\006" +
    "\000\002\007\006\000\002\010\006\000\002\011\015\000" +
    "\002\105\003\000\002\105\002\000\002\106\003\000\002" +
    "\106\002\000\002\107\003\000\002\107\002\000\002\110" +
    "\003\000\002\110\002\000\002\111\003\000\002\111\002" +
    "\000\002\112\003\000\002\112\002\000\002\113\003\000" +
    "\002\113\002\000\002\114\003\000\002\114\002\000\002" +
    "\115\003\000\002\115\002\000\002\116\003\000\002\116" +
    "\002\000\002\117\003\000\002\117\002\000\002\120\003" +
    "\000\002\120\002\000\002\121\003\000\002\121\002\000" +
    "\002\123\003\000\002\123\002\000\002\012\012\000\002" +
    "\013\006\000\002\013\006\000\002\014\006\000\002\015" +
    "\010\000\002\016\006\000\002\016\006\000\002\017\010" +
    "\000\002\020\006\000\002\021\006\000\002\022\006\000" +
    "\002\022\005\000\002\022\004\000\002\023\006\000\002" +
    "\024\006\000\002\025\006\000\002\026\007\000\002\026" +
    "\006\000\002\056\004\000\002\056\003\000\002\057\004" +
    "\000\002\057\003\000\002\060\003\000\002\060\002\000" +
    "\002\027\007\000\002\061\004\000\002\061\003\000\002" +
    "\063\003\000\002\063\002\000\002\062\004\000\002\062" +
    "\003\000\002\030\012\000\002\031\006\000\002\031\006" +
    "\000\002\032\006\000\002\032\006\000\002\033\006\000" +
    "\002\033\006\000\002\034\006\000\002\034\006\000\002" +
    "\035\006\000\002\064\004\000\002\064\003\000\002\036" +
    "\010\000\002\037\006\000\002\040\012\000\002\041\006" +
    "\000\002\043\011\000\002\044\006\000\002\044\006\000" +
    "\002\045\006\000\002\045\006\000\002\046\011\000\002" +
    "\047\006\000\002\047\006\000\002\050\007\000\002\050" +
    "\006\000\002\065\004\000\002\065\003\000\002\066\003" +
    "\000\002\066\002\000\002\051\007\000\002\071\005\000" +
    "\002\071\002\000\002\052\006\000\002\067\004\000\002" +
    "\067\003\000\002\053\006\000\002\054\006\000\002\054" +
    "\006\000\002\055\011\000\002\070\005\000\002\070\006" +
    "\000\002\076\007\000\002\076\006\000\002\072\004\000" +
    "\002\072\003\000\002\073\004\000\002\073\003\000\002" +
    "\074\003\000\002\074\002\000\002\077\013\000\002\100" +
    "\006\000\002\100\006\000\002\101\006\000\002\075\004" +
    "\000\002\075\003\000\002\102\007\000\002\103\006\000" +
    "\002\103\006\000\002\104\007\000\002\042\006" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\u0141\000\006\004\005\006\007\001\002\000\004\073" +
    "\u0140\001\002\000\004\103\023\001\002\000\004\002\uffff" +
    "\001\002\000\004\064\014\001\002\000\004\002\013\001" +
    "\002\000\004\004\005\001\002\000\004\002\000\001\002" +
    "\000\004\002\001\001\002\000\004\103\016\001\002\000" +
    "\004\065\022\001\002\000\004\070\017\001\002\000\002" +
    "\001\002\000\004\071\021\001\002\000\004\065\ufffa\001" +
    "\002\000\004\004\ufffc\001\002\000\004\064\024\001\002" +
    "\000\004\007\025\001\002\000\004\064\u013d\001\002\000" +
    "\004\010\027\001\002\000\004\064\u0111\001\002\000\004" +
    "\024\031\001\002\000\004\064\343\001\002\000\014\035" +
    "\033\040\ufff7\046\ufff7\054\ufff7\065\ufff7\001\002\000\004" +
    "\064\315\001\002\000\012\040\ufff8\046\ufff8\054\ufff8\065" +
    "\ufff8\001\002\000\012\040\037\046\ufff5\054\ufff5\065\ufff5" +
    "\001\002\000\010\046\ufff6\054\ufff6\065\ufff6\001\002\000" +
    "\004\064\235\001\002\000\010\046\041\054\ufff3\065\ufff3" +
    "\001\002\000\004\064\206\001\002\000\006\054\ufff4\065" +
    "\ufff4\001\002\000\006\054\044\065\ufff1\001\002\000\004" +
    "\064\050\001\002\000\004\065\047\001\002\000\004\065" +
    "\ufff2\001\002\000\004\073\ufff9\001\002\000\006\055\055" +
    "\062\054\001\002\000\006\062\uff8e\065\uff8e\001\002\000" +
    "\006\062\054\065\205\001\002\000\010\055\055\062\054" +
    "\065\uff8c\001\002\000\004\064\174\001\002\000\004\064" +
    "\057\001\002\000\010\055\uff90\062\uff90\065\uff90\001\002" +
    "\000\004\056\060\001\002\000\004\066\167\001\002\000" +
    "\006\030\uffdd\057\062\001\002\000\004\064\142\001\002" +
    "\000\004\030\066\001\002\000\004\030\uffde\001\002\000" +
    "\004\053\074\001\002\000\004\066\067\001\002\000\004" +
    "\103\070\001\002\000\004\067\073\001\002\000\004\067" +
    "\072\001\002\000\014\013\uffb8\031\uffb8\034\uffb8\053\uffb8" +
    "\065\uffb8\001\002\000\014\013\uffb7\031\uffb7\034\uffb7\053" +
    "\uffb7\065\uffb7\001\002\000\004\064\114\001\002\000\004" +
    "\061\077\001\002\000\006\023\107\065\uffe9\001\002\000" +
    "\004\066\100\001\002\000\004\103\101\001\002\000\004" +
    "\067\104\001\002\000\004\067\103\001\002\000\006\023" +
    "\uff84\065\uff84\001\002\000\006\023\uff83\065\uff83\001\002" +
    "\000\004\065\uffea\001\002\000\004\065\113\001\002\000" +
    "\004\066\110\001\002\000\004\077\111\001\002\000\004" +
    "\067\112\001\002\000\004\065\uffcd\001\002\000\010\055" +
    "\uff8b\062\uff8b\065\uff8b\001\002\000\004\056\060\001\002" +
    "\000\004\051\116\001\002\000\004\066\135\001\002\000" +
    "\004\052\120\001\002\000\004\066\132\001\002\000\004" +
    "\072\123\001\002\000\006\065\126\072\127\001\002\000" +
    "\004\051\116\001\002\000\004\052\120\001\002\000\006" +
    "\065\uff95\072\uff95\001\002\000\010\053\uff96\061\uff96\065" +
    "\uff96\001\002\000\004\051\116\001\002\000\004\052\120" +
    "\001\002\000\006\065\uff94\072\uff94\001\002\000\004\074" +
    "\133\001\002\000\004\067\134\001\002\000\006\065\uff99" +
    "\072\uff99\001\002\000\004\103\136\001\002\000\004\067" +
    "\141\001\002\000\004\067\140\001\002\000\010\052\uff98" +
    "\065\uff98\072\uff98\001\002\000\010\052\uff97\065\uff97\072" +
    "\uff97\001\002\000\004\060\144\001\002\000\006\060\144" +
    "\065\165\001\002\000\004\064\146\001\002\000\006\060" +
    "\uff86\065\uff86\001\002\000\004\011\147\001\002\000\004" +
    "\066\160\001\002\000\006\022\152\065\uffeb\001\002\000" +
    "\004\065\157\001\002\000\004\066\154\001\002\000\006" +
    "\023\uffec\065\uffec\001\002\000\004\077\155\001\002\000" +
    "\004\067\156\001\002\000\006\023\uffce\065\uffce\001\002" +
    "\000\006\060\uff85\065\uff85\001\002\000\004\103\162\001" +
    "\002\000\004\067\164\001\002\000\004\067\163\001\002" +
    "\000\012\012\uffda\013\uffda\022\uffda\065\uffda\001\002\000" +
    "\012\012\uffdb\013\uffdb\022\uffdb\065\uffdb\001\002\000\004" +
    "\030\uff88\001\002\000\006\060\uff87\065\uff87\001\002\000" +
    "\004\103\170\001\002\000\004\067\173\001\002\000\004" +
    "\067\172\001\002\000\012\030\uff8a\037\uff8a\051\uff8a\057" +
    "\uff8a\001\002\000\012\030\uff89\037\uff89\051\uff89\057\uff89" +
    "\001\002\000\004\056\060\001\002\000\004\030\066\001" +
    "\002\000\004\065\177\001\002\000\006\062\uff82\065\uff82" +
    "\001\002\000\006\062\054\065\uff8d\001\002\000\004\065" +
    "\203\001\002\000\010\055\uff91\062\uff91\065\uff91\001\002" +
    "\000\004\065\uff93\001\002\000\006\062\uff8f\065\uff8f\001" +
    "\002\000\004\065\uff92\001\002\000\006\047\212\050\211" +
    "\001\002\000\006\050\211\065\234\001\002\000\006\050" +
    "\211\065\uffa0\001\002\000\004\064\223\001\002\000\004" +
    "\064\214\001\002\000\006\050\uffa2\065\uffa2\001\002\000" +
    "\004\051\116\001\002\000\006\065\uff9d\072\217\001\002" +
    "\000\004\065\222\001\002\000\004\051\116\001\002\000" +
    "\006\065\uff9d\072\217\001\002\000\004\065\uff9e\001\002" +
    "\000\006\050\uff9f\065\uff9f\001\002\000\004\053\074\001" +
    "\002\000\006\053\074\065\226\001\002\000\006\053\uff9a" +
    "\065\uff9a\001\002\000\006\050\uff9c\065\uff9c\001\002\000" +
    "\006\053\uff9b\065\uff9b\001\002\000\006\050\211\065\uffa1" +
    "\001\002\000\004\065\232\001\002\000\006\054\uffa5\065" +
    "\uffa5\001\002\000\006\050\uffa3\065\uffa3\001\002\000\006" +
    "\054\uffa4\065\uffa4\001\002\000\006\041\241\044\243\001" +
    "\002\000\006\044\243\065\314\001\002\000\010\041\241" +
    "\044\243\065\uffc5\001\002\000\006\044\uffc7\065\uffc7\001" +
    "\002\000\004\064\272\001\002\000\010\041\uffc9\044\uffc9" +
    "\065\uffc9\001\002\000\004\064\244\001\002\000\004\042" +
    "\245\001\002\000\004\066\265\001\002\000\004\030\066" +
    "\001\002\000\004\034\250\001\002\000\004\066\262\001" +
    "\002\000\004\045\252\001\002\000\004\066\255\001\002" +
    "\000\004\065\254\001\002\000\006\044\uffa8\065\uffa8\001" +
    "\002\000\004\103\256\001\002\000\004\067\261\001\002" +
    "\000\004\067\260\001\002\000\006\043\uffa7\065\uffa7\001" +
    "\002\000\006\043\uffa6\065\uffa6\001\002\000\004\063\263" +
    "\001\002\000\004\067\264\001\002\000\006\013\uff81\045" +
    "\uff81\001\002\000\004\103\266\001\002\000\004\067\271" +
    "\001\002\000\004\067\270\001\002\000\006\030\uffac\034" +
    "\uffac\001\002\000\006\030\uffab\034\uffab\001\002\000\004" +
    "\042\245\001\002\000\004\034\250\001\002\000\004\045" +
    "\252\001\002\000\006\043\300\065\uffdf\001\002\000\004" +
    "\065\uffe0\001\002\000\004\065\306\001\002\000\004\066" +
    "\301\001\002\000\004\103\302\001\002\000\004\067\305" +
    "\001\002\000\004\067\304\001\002\000\004\065\uffaa\001" +
    "\002\000\004\065\uffa9\001\002\000\010\041\uffad\044\uffad" +
    "\065\uffad\001\002\000\006\044\243\065\uffc6\001\002\000" +
    "\004\065\312\001\002\000\010\041\uffca\044\uffca\065\uffca" +
    "\001\002\000\010\046\uffcc\054\uffcc\065\uffcc\001\002\000" +
    "\006\044\uffc8\065\uffc8\001\002\000\010\046\uffcb\054\uffcb" +
    "\065\uffcb\001\002\000\004\036\316\001\002\000\004\064" +
    "\323\001\002\000\006\036\uffb2\065\uffb2\001\002\000\006" +
    "\036\316\065\322\001\002\000\006\036\uffb3\065\uffb3\001" +
    "\002\000\012\040\uffb4\046\uffb4\054\uffb4\065\uffb4\001\002" +
    "\000\004\056\060\001\002\000\004\037\326\001\002\000" +
    "\006\027\332\065\uffe7\001\002\000\004\066\327\001\002" +
    "\000\004\075\330\001\002\000\004\067\331\001\002\000" +
    "\006\027\uffb0\065\uffb0\001\002\000\004\066\336\001\002" +
    "\000\004\065\uffe8\001\002\000\004\065\335\001\002\000" +
    "\006\036\uffb1\065\uffb1\001\002\000\004\103\340\001\002" +
    "\000\004\067\342\001\002\000\004\067\341\001\002\000" +
    "\014\013\uffb9\030\uffb9\031\uffb9\034\uffb9\065\uffb9\001\002" +
    "\000\014\013\uffba\030\uffba\031\uffba\034\uffba\065\uffba\001" +
    "\002\000\004\025\346\001\002\000\010\025\346\032\u0105" +
    "\065\uffc0\001\002\000\010\025\uffc2\032\uffc2\065\uffc2\001" +
    "\002\000\004\064\347\001\002\000\004\026\350\001\002" +
    "\000\004\066\375\001\002\000\004\027\332\001\002\000" +
    "\010\013\uffe5\030\066\031\uffe5\001\002\000\006\013\uffe6" +
    "\031\uffe6\001\002\000\006\013\uffe3\031\357\001\002\000" +
    "\004\013\uffe4\001\002\000\004\013\366\001\002\000\004" +
    "\066\360\001\002\000\004\103\361\001\002\000\004\067" +
    "\364\001\002\000\004\067\363\001\002\000\004\013\uffb6" +
    "\001\002\000\004\013\uffb5\001\002\000\004\065\374\001" +
    "\002\000\004\066\367\001\002\000\004\100\370\001\002" +
    "\000\004\101\371\001\002\000\004\102\372\001\002\000" +
    "\004\067\373\001\002\000\010\014\uffd8\015\uffd8\065\uffd8" +
    "\001\002\000\010\025\uffbd\032\uffbd\065\uffbd\001\002\000" +
    "\004\103\377\001\002\000\004\067\u0101\001\002\000\004" +
    "\067\u0100\001\002\000\004\027\uffbb\001\002\000\004\027" +
    "\uffbc\001\002\000\006\032\u0105\065\uffc1\001\002\000\006" +
    "\032\uffbe\065\uffbe\001\002\000\010\025\uffc3\032\uffc3\065" +
    "\uffc3\001\002\000\004\064\u0108\001\002\000\004\065\u0107" +
    "\001\002\000\014\035\uffc4\040\uffc4\046\uffc4\054\uffc4\065" +
    "\uffc4\001\002\000\004\026\350\001\002\000\002\001\002" +
    "\000\004\027\332\001\002\000\006\013\uffe1\034\250\001" +
    "\002\000\004\013\uffe2\001\002\000\004\013\366\001\002" +
    "\000\004\065\u010f\001\002\000\006\032\uffaf\065\uffaf\001" +
    "\002\000\006\032\uffbf\065\uffbf\001\002\000\004\011\147" +
    "\001\002\000\006\012\u0113\013\uffef\001\002\000\004\066" +
    "\u013a\001\002\000\004\013\ufff0\001\002\000\004\013\366" +
    "\001\002\000\006\014\u0117\015\uffed\001\002\000\004\066" +
    "\u0135\001\002\000\004\015\uffee\001\002\000\004\015\u011b" +
    "\001\002\000\004\065\u0134\001\002\000\004\064\u011c\001" +
    "\002\000\004\016\u011e\001\002\000\004\017\u0123\001\002" +
    "\000\004\066\u011f\001\002\000\004\076\u0120\001\002\000" +
    "\004\067\u0121\001\002\000\004\017\uffd4\001\002\000\004" +
    "\020\u0128\001\002\000\004\066\u0124\001\002\000\004\105" +
    "\u0125\001\002\000\004\067\u0126\001\002\000\004\020\uffd3" +
    "\001\002\000\004\065\u0133\001\002\000\010\021\u012a\022" +
    "\152\023\107\001\002\000\004\065\uffd0\001\002\000\004" +
    "\066\u0130\001\002\000\010\022\152\023\uffeb\065\uffeb\001" +
    "\002\000\006\023\107\065\uffe9\001\002\000\004\065\uffd1" +
    "\001\002\000\006\023\107\065\uffe9\001\002\000\004\065" +
    "\uffd2\001\002\000\004\077\u0131\001\002\000\004\067\u0132" +
    "\001\002\000\010\022\uffcf\023\uffcf\065\uffcf\001\002\000" +
    "\004\065\uffd5\001\002\000\004\024\uffdc\001\002\000\004" +
    "\103\u0136\001\002\000\004\067\u0139\001\002\000\004\067" +
    "\u0138\001\002\000\004\015\uffd7\001\002\000\004\015\uffd6" +
    "\001\002\000\004\077\u013b\001\002\000\004\067\u013c\001" +
    "\002\000\004\013\uffd9\001\002\000\004\103\016\001\002" +
    "\000\004\065\u013f\001\002\000\004\010\ufffb\001\002\000" +
    "\004\005\u0141\001\002\000\004\073\u0142\001\002\000\006" +
    "\002\ufffd\004\005\001\002\000\004\002\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\u0141\000\012\004\007\005\005\006\010\011\003\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\005\011\011" +
    "\003\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\010\014\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\003\017\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\007\025\001" +
    "\001\000\002\001\001\000\004\012\027\001\001\000\002" +
    "\001\001\000\004\027\031\001\001\000\002\001\001\000" +
    "\006\035\033\105\034\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\026\035\106\037\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\050\041\107\042\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\076\045\110" +
    "\044\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\072\052\073\051\077" +
    "\055\104\050\001\001\000\002\001\001\000\004\104\203" +
    "\001\001\000\012\073\177\074\200\077\201\104\050\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\100\060\001\001\000\002\001\001\000\006\101" +
    "\063\123\062\001\001\000\002\001\001\000\004\033\064" +
    "\001\001\000\002\001\001\000\004\055\074\001\001\000" +
    "\002\001\001\000\004\003\070\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\103\075\001\001\000\006\025\104" +
    "\114\105\001\001\000\002\001\001\000\004\003\101\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\100\114\001\001\000" +
    "\004\054\116\001\001\000\002\001\001\000\004\053\120" +
    "\001\001\000\002\001\001\000\004\070\121\001\001\000" +
    "\002\001\001\000\004\054\123\001\001\000\004\053\124" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\054" +
    "\127\001\001\000\004\053\130\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\003\136\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\075\142\102" +
    "\144\001\001\000\004\102\165\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\013\147\001\001\000\002\001" +
    "\001\000\006\024\152\113\150\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\002\160\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\003\170\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\100\174\001\001\000\004\033\175\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\104\203\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\051\207\052\212\065\206" +
    "\001\001\000\004\052\232\001\001\000\010\052\212\065" +
    "\227\066\230\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\054\214\001\001\000\004\071" +
    "\215\001\001\000\002\001\001\000\004\054\217\001\001" +
    "\000\004\071\220\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\055\224\067\223\001\001\000\004\055\226" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\052\232\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\043" +
    "\241\046\237\056\236\057\235\001\001\000\004\046\312" +
    "\001\001\000\012\043\310\046\237\057\306\060\307\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\044\245\001\001\000\002\001" +
    "\001\000\004\033\246\001\001\000\004\042\250\001\001" +
    "\000\002\001\001\000\004\047\252\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\003\256" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\003\266\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\044\272\001\001\000\004\042\273\001\001\000" +
    "\004\047\274\001\001\000\006\045\275\121\276\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\003\302\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\046\312\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\036\316\064\317\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\036\320\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\100\323\001\001\000\004\037\324" +
    "\001\001\000\006\032\332\115\333\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\002\336\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\030\344\061\343\001\001\000\012\030\u0103\040\u0102" +
    "\062\u0101\063\u0105\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\031\350\001\001\000\002\001\001\000\004" +
    "\032\351\001\001\000\006\033\352\116\353\001\001\000" +
    "\002\001\001\000\006\034\354\117\355\001\001\000\002" +
    "\001\001\000\004\015\364\001\001\000\002\001\001\000" +
    "\004\003\361\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\002\375\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\040" +
    "\u010f\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\031" +
    "\u0108\001\001\000\004\122\u0109\001\001\000\004\032\u010a" +
    "\001\001\000\006\042\u010b\120\u010c\001\001\000\002\001" +
    "\001\000\004\015\u010d\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\013\u0111\001\001\000" +
    "\006\014\u0113\111\u0114\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\015\u0115\001\001\000\006\016\u0117\112" +
    "\u0118\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\017\u0119\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\020\u011c\001\001\000\004\021\u0121\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\022\u0126\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\023\u012a\024\u012b\025\u0128\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\024\152\113\u012d\001" +
    "\001\000\006\025\104\114\u012c\001\001\000\002\001\001" +
    "\000\006\025\104\114\u012e\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\003\u0136\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\010\u013d\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\005" +
    "\u0142\011\003\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public static void main(String args[]) throws Exception {
        FileInputStream stream = new FileInputStream(args[0]);
        Reader reader = new InputStreamReader(stream);

        try {
            new parser(new Yylex(reader)).parse();
        } catch (Exception e) {
            System.out.println("Analisis INCORRECTO !!");
            System.exit(1);
        }
        System.out.println("Analisis Correcto ");
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= cvs EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // cvs ::= global_var cv_list 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cvs",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // cvs ::= cv_list 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cvs",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // cv_list ::= cv CD ID CD cv_list 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cv_list",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // cv_list ::= cv CD ID CD 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cv_list",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // global_var ::= GVAR LL_A variable LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("global_var",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // local_var ::= LVAR LL_A variable LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("local_var",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // variable ::= IDENT IG CONJPALYNUM PYC 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("variable",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // cv ::= CV IDENT LL_A local_var datospersonales formacion idiomas_opt experiencia_opt habilidades_opt portafolio_opt LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cv",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // idiomas_opt ::= idiomas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("idiomas_opt",67, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // idiomas_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("idiomas_opt",67, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // experiencia_opt ::= experiencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("experiencia_opt",68, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // experiencia_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("experiencia_opt",68, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // habilidades_opt ::= habilidades 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("habilidades_opt",69, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // habilidades_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("habilidades_opt",69, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // portafolio_opt ::= portafolio 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("portafolio_opt",70, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // portafolio_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("portafolio_opt",70, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // foto_opt ::= foto 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("foto_opt",71, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // foto_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("foto_opt",71, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // bio_opt ::= bio 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bio_opt",72, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // bio_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bio_opt",72, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // github_opt ::= github 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("github_opt",73, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // github_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("github_opt",73, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // web_opt ::= web 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("web_opt",74, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // web_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("web_opt",74, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expedidor_opt ::= expedidor 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expedidor_opt",75, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expedidor_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expedidor_opt",75, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // descripcion_opt ::= descripcion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("descripcion_opt",76, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // descripcion_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("descripcion_opt",76, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // logros_opt ::= logros 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("logros_opt",77, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // logros_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("logros_opt",77, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // horas_opt ::= horas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("horas_opt",78, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // horas_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("horas_opt",78, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // responsabilidades_opt ::= responsabilidades 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("responsabilidades_opt",79, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // responsabilidades_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("responsabilidades_opt",79, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // grupo_opt ::= grupo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("grupo_opt",81, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // grupo_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("grupo_opt",81, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // datospersonales ::= DP LL_A nomyape foto_opt fecha bio_opt contacto LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("datospersonales",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // nomyape ::= NOMYAPE PA_A CONJPAL PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nomyape",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // nomyape ::= NOMYAPE PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nomyape",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // foto ::= FOTO PA_A RUTA PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("foto",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // fecha ::= FECHA PA_A DIA MES ANIO PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("fecha",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // bio ::= BIO PA_A CONJPALYNUM PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bio",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // bio ::= BIO PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bio",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // contacto ::= CONTACTO LL_A email telefono redes LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("contacto",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // email ::= EMAIL PA_A MAIL PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("email",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // telefono ::= TELEFONO PA_A TFNO PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("telefono",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // redes ::= REDES linkedin github_opt web_opt 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("redes",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // redes ::= REDES github web_opt 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("redes",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // redes ::= REDES web 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("redes",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // linkedin ::= LINKEDIN PA_A RUTA PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("linkedin",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // github ::= GITHUB PA_A RUTA PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("github",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // web ::= WEB PA_A RUTA PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("web",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // experiencia ::= EXPERIENCIA LL_A laboral_list voluntariado_opt_list LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("experiencia",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // experiencia ::= EXPERIENCIA LL_A voluntariado_list LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("experiencia",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // laboral_list ::= laboral_list laboral 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("laboral_list",44, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // laboral_list ::= laboral 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("laboral_list",44, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // voluntariado_list ::= voluntariado_list voluntariado 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("voluntariado_list",45, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // voluntariado_list ::= voluntariado 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("voluntariado_list",45, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // voluntariado_opt_list ::= voluntariado_list 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("voluntariado_opt_list",46, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // voluntariado_opt_list ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("voluntariado_opt_list",46, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // formacion ::= FORMACION LL_A oficial_list complementaria_opt_list LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("formacion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // oficial_list ::= oficial_list oficial 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("oficial_list",47, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // oficial_list ::= oficial 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("oficial_list",47, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // complementaria_opt_list ::= complementaria_list 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("complementaria_opt_list",49, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // complementaria_opt_list ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("complementaria_opt_list",49, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // complementaria_list ::= complementaria_list complementaria 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("complementaria_list",48, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // complementaria_list ::= complementaria 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("complementaria_list",48, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // oficial ::= OFICIAL LL_A titulo expedidor descripcion_opt logros_opt fecha LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("oficial",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // titulo ::= TITULO PA_A CONJPAL PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("titulo",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // titulo ::= TITULO PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("titulo",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expedidor ::= EXPEDIDOR PA_A CONJPAL PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expedidor",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // expedidor ::= EXPEDIDOR PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expedidor",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // descripcion ::= DESCRIPCION PA_A CONJPALYNUM PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("descripcion",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // descripcion ::= DESCRIPCION PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("descripcion",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // logros ::= LOGROS PA_A CONJPALYNUM PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("logros",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // logros ::= LOGROS PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("logros",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // idiomas ::= IDIOMAS LL_A idioma_list LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("idiomas",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // idioma_list ::= idioma_list idioma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("idioma_list",50, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // idioma_list ::= idioma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("idioma_list",50, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // idioma ::= IDIOMA LL_A nombre nvi expedidor_opt LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("idioma",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // nvi ::= NIVEL PA_A NVI PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nvi",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // complementaria ::= COMPLEMENTARIA LL_A titulo certificado_opt expedidor horas_opt fecha LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("complementaria",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // certificado ::= CERTIFICADO PA_A BOOL PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("certificado",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // laboral ::= LABORAL LL_A puesto horas organizacion responsabilidades_opt LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("laboral",33, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // puesto ::= PUESTO PA_A CONJPALYNUM PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("puesto",34, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // puesto ::= PUESTO PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("puesto",34, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // responsabilidades ::= RESPONSABILIDADES PA_A CONJPALYNUM PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("responsabilidades",35, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // responsabilidades ::= RESPONSABILIDADES PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("responsabilidades",35, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // voluntariado ::= VOLUNTARIADO LL_A puesto descripcion horas organizacion LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("voluntariado",36, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // organizacion ::= ORGANIZACION PA_A CONJPALYNUM PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("organizacion",37, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // organizacion ::= ORGANIZACION PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("organizacion",37, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // habilidades ::= HABILIDADES LL_A soft hard_opt_list LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("habilidades",38, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // habilidades ::= HABILIDADES LL_A hard_list LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("habilidades",38, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 94: // hard_list ::= hard_list hard 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("hard_list",51, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 95: // hard_list ::= hard 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("hard_list",51, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 96: // hard_opt_list ::= hard_list 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("hard_opt_list",52, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 97: // hard_opt_list ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("hard_opt_list",52, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 98: // soft ::= SOFT LL_A habilidad soft_hab_tail LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("soft",39, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 99: // soft_hab_tail ::= CO habilidad soft_hab_tail 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("soft_hab_tail",55, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 100: // soft_hab_tail ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("soft_hab_tail",55, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 101: // hard ::= HARD LL_A categoria_list LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("hard",40, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 102: // categoria_list ::= categoria_list categoria 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("categoria_list",53, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 103: // categoria_list ::= categoria 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("categoria_list",53, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 104: // nvh ::= NVHAB PA_A NVH PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nvh",41, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 105: // habilidad ::= HABILIDAD PA_A CONJPALYNUM PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("habilidad",42, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 106: // habilidad ::= HABILIDAD PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("habilidad",42, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 107: // categoria ::= CATEGORIA LL_A nombre habilidad nvh categoria_tail LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("categoria",43, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 108: // categoria_tail ::= CO habilidad nvh 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("categoria_tail",54, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 109: // categoria_tail ::= categoria_tail CO habilidad nvh 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("categoria_tail",54, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 110: // portafolio ::= PORTAFOLIO LL_A proyecto_list merito_opt_list LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("portafolio",60, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 111: // portafolio ::= PORTAFOLIO LL_A merito_list LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("portafolio",60, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 112: // proyecto_list ::= proyecto_list proyecto 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("proyecto_list",56, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 113: // proyecto_list ::= proyecto 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("proyecto_list",56, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 114: // merito_list ::= merito_list merito 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("merito_list",57, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 115: // merito_list ::= merito 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("merito_list",57, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 116: // merito_opt_list ::= merito_list 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("merito_opt_list",58, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 117: // merito_opt_list ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("merito_opt_list",58, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 118: // proyecto ::= PROYECTO LL_A nombre grupo_opt descripcion categoria tecnologias web_opt LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("proyecto",61, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 119: // nombre ::= NOMBRE PA_A CONJPALYNUM PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nombre",62, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 120: // nombre ::= NOMBRE PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nombre",62, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 121: // grupo ::= GRUPO LL_A companero_list LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("grupo",63, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 122: // companero_list ::= companero_list companero 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("companero_list",59, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 123: // companero_list ::= companero 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("companero_list",59, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 124: // companero ::= COMPANERO LL_A nomyape github_opt LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("companero",64, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 125: // tecnologias ::= TECNOLOGIAS PA_A CONJPALYNUM PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tecnologias",65, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 126: // tecnologias ::= TECNOLOGIAS PA_A IDENT PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tecnologias",65, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 127: // merito ::= MERITOS LL_A nombre descripcion LL_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("merito",66, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 128: // horas ::= HORAS PA_A NUM PA_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("horas",32, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
