
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 10 10:53:20 CET 2026
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NOMYAPE = 6;
  public static final int DESCRIPCION = 21;
  public static final int TECNOLOGIAS = 46;
  public static final int IDIOMA = 27;
  public static final int TFNO = 65;
  public static final int GVAR = 3;
  public static final int NOMBRE = 43;
  public static final int NVI = 57;
  public static final int NVH = 56;
  public static final int HORAS = 25;
  public static final int LVAR = 4;
  public static final int PROYECTO = 42;
  public static final int SOFT = 36;
  public static final int ORGANIZACION = 34;
  public static final int CV = 2;
  public static final int FECHA = 8;
  public static final int PORTAFOLIO = 41;
  public static final int CO = 55;
  public static final int NIVEL = 28;
  public static final int FOTO = 7;
  public static final int GITHUB = 15;
  public static final int BOOL = 64;
  public static final int CERTIFICADO = 24;
  public static final int TELEFONO = 12;
  public static final int OFICIAL = 18;
  public static final int TITULO = 19;
  public static final int CONTACTO = 10;
  public static final int NUM = 48;
  public static final int IG = 53;
  public static final int HABILIDADES = 35;
  public static final int GRUPO = 44;
  public static final int MAIL = 58;
  public static final int CATEGORIA = 40;
  public static final int EOF = 0;
  public static final int PUESTO = 31;
  public static final int error = 1;
  public static final int HARD = 37;
  public static final int EMAIL = 11;
  public static final int CONJPALYNUM = 67;
  public static final int LABORAL = 30;
  public static final int IDENT = 63;
  public static final int PA_C = 52;
  public static final int LOGROS = 22;
  public static final int DIA = 60;
  public static final int FORMACION = 17;
  public static final int REDES = 13;
  public static final int PA_A = 51;
  public static final int EXPERIENCIA = 29;
  public static final int LINKEDIN = 14;
  public static final int VOLUNTARIADO = 33;
  public static final int CONJPAL = 66;
  public static final int MES = 61;
  public static final int LL_C = 50;
  public static final int BIO = 9;
  public static final int LL_A = 49;
  public static final int NVHAB = 39;
  public static final int WEB = 16;
  public static final int RESPONSABILIDADES = 32;
  public static final int RUTA = 59;
  public static final int IDIOMAS = 26;
  public static final int COMPANERO = 45;
  public static final int MERITOS = 47;
  public static final int EXPEDIDOR = 20;
  public static final int HABILIDAD = 38;
  public static final int DP = 5;
  public static final int PYC = 54;
  public static final int ANIO = 62;
  public static final int COMPLEMENTARIA = 23;
}

