
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NOMYAPE = 7;
  public static final int DESCRIPCION = 22;
  public static final int TECNOLOGIAS = 47;
  public static final int IDIOMA = 28;
  public static final int TFNO = 67;
  public static final int GVAR = 4;
  public static final int NOMBRE = 44;
  public static final int NVI = 59;
  public static final int NVH = 58;
  public static final int HORAS = 26;
  public static final int LVAR = 5;
  public static final int PROYECTO = 43;
  public static final int SOFT = 37;
  public static final int ORGANIZACION = 35;
  public static final int CV = 2;
  public static final int FECHA = 9;
  public static final int PORTAFOLIO = 42;
  public static final int CO = 56;
  public static final int NIVEL = 29;
  public static final int FOTO = 8;
  public static final int GITHUB = 16;
  public static final int BOOL = 66;
  public static final int CERTIFICADO = 25;
  public static final int TELEFONO = 13;
  public static final int OFICIAL = 19;
  public static final int TITULO = 20;
  public static final int CONTACTO = 11;
  public static final int CD = 57;
  public static final int NUM = 49;
  public static final int IG = 54;
  public static final int HABILIDADES = 36;
  public static final int GRUPO = 45;
  public static final int MAIL = 60;
  public static final int CATEGORIA = 41;
  public static final int ID = 3;
  public static final int EOF = 0;
  public static final int PUESTO = 32;
  public static final int error = 1;
  public static final int HARD = 38;
  public static final int EMAIL = 12;
  public static final int LABORAL = 31;
  public static final int IDENT = 65;
  public static final int PA_C = 53;
  public static final int LOGROS = 23;
  public static final int DIA = 62;
  public static final int FORMACION = 18;
  public static final int REDES = 14;
  public static final int PA_A = 52;
  public static final int EXPERIENCIA = 30;
  public static final int LINKEDIN = 15;
  public static final int VOLUNTARIADO = 34;
  public static final int MES = 63;
  public static final int LL_C = 51;
  public static final int BIO = 10;
  public static final int LL_A = 50;
  public static final int NVHAB = 40;
  public static final int WEB = 17;
  public static final int RESPONSABILIDADES = 33;
  public static final int RUTA = 61;
  public static final int IDIOMAS = 27;
  public static final int COMPANERO = 46;
  public static final int MERITOS = 48;
  public static final int EXPEDIDOR = 21;
  public static final int HABILIDAD = 39;
  public static final int DP = 6;
  public static final int PYC = 55;
  public static final int ANIO = 64;
  public static final int COMPLEMENTARIA = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CV",
  "ID",
  "GVAR",
  "LVAR",
  "DP",
  "NOMYAPE",
  "FOTO",
  "FECHA",
  "BIO",
  "CONTACTO",
  "EMAIL",
  "TELEFONO",
  "REDES",
  "LINKEDIN",
  "GITHUB",
  "WEB",
  "FORMACION",
  "OFICIAL",
  "TITULO",
  "EXPEDIDOR",
  "DESCRIPCION",
  "LOGROS",
  "COMPLEMENTARIA",
  "CERTIFICADO",
  "HORAS",
  "IDIOMAS",
  "IDIOMA",
  "NIVEL",
  "EXPERIENCIA",
  "LABORAL",
  "PUESTO",
  "RESPONSABILIDADES",
  "VOLUNTARIADO",
  "ORGANIZACION",
  "HABILIDADES",
  "SOFT",
  "HARD",
  "HABILIDAD",
  "NVHAB",
  "CATEGORIA",
  "PORTAFOLIO",
  "PROYECTO",
  "NOMBRE",
  "GRUPO",
  "COMPANERO",
  "TECNOLOGIAS",
  "MERITOS",
  "NUM",
  "LL_A",
  "LL_C",
  "PA_A",
  "PA_C",
  "IG",
  "PYC",
  "CO",
  "CD",
  "NVH",
  "NVI",
  "MAIL",
  "RUTA",
  "DIA",
  "MES",
  "ANIO",
  "IDENT",
  "BOOL",
  "TFNO"
  };
}

